#!/bin/sh

_enter() {
        local script_path
        local script_dir
        script_path=`readlink -f $0`
        script_dir=`dirname $script_path`
        _wd=`pwd`
        cd $script_dir/modules
}

_leave() { # move back to initial wd
        cd $_wd
}

_main() {
        for MOD in ./*
        do
                if [ -d $MOD ]
                then
                        cd $MOD
                        $*
                        cd ..
                fi
        done
}

_enter
_main $*
_leave
