#!/bin/sh

[ -z "$1" ] && echo missing branch && exit 1

git submodule foreach git fetch -p &&
	git submodule foreach git checkout "$1" &&
	git submodule foreach git merge origin/"$1" &&
	git status

